require 'colorize'

puts "This is light blue".colorize(:light_blue)
sleep(0.5)
puts "This is blue".colorize(:blue)
sleep(0.5)
puts "This is green".colorize(:green)
sleep(0.5)
puts "This is yellow".colorize(:yellow)
sleep(0.5)
puts "This is red".colorize(:red)
sleep(0.5)
puts "This is pink".colorize(:pink)
sleep(0.5)
puts "This is white with  background".colorize(:color => :black, :background => :white)